const DBKEY="ghaim_fee_data_v1";
const SETTINGS_KEY="ghaim_fee_settings_v1";
const AUTH_KEY="ghaim_auth_v1";
const DEFAULT_SETTINGS={loginCode:"1234",levels:["تمهيدي","KG1","KG2","KG3"],methods:["بنكي","شبكة","قرة","تابي"]};
const EMPTY={students:[],payments:[]};
let cloudSyncing=false;
let cloudPromise=null;
function esc(v){return String(v??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));}
function db(){try{const d=JSON.parse(localStorage.getItem(DBKEY)||"null");return {students:Array.isArray(d?.students)?d.students:[],payments:Array.isArray(d?.payments)?d.payments:[]};}catch(e){return JSON.parse(JSON.stringify(EMPTY));}}
function saveDB(d){localStorage.setItem(DBKEY,JSON.stringify(d));}
function settings(){try{return {...DEFAULT_SETTINGS,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}")};}catch(e){return {...DEFAULT_SETTINGS};}}
function saveSettings(s){localStorage.setItem(SETTINGS_KEY,JSON.stringify(s));}
function money(n){const x=Number(n);return Number.isFinite(x)?x.toLocaleString("ar-SA",{maximumFractionDigits:2}):"0";}
function localDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`;}
function today(){return localDate();}
function addDays(date,n){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+n);return localDate(d);}
function weekday(date){return new Intl.DateTimeFormat("ar-SA",{weekday:"long"}).format(new Date(`${date}T12:00:00`));}
function nextWorkday(date){let d=date;do{d=addDays(d,1);}while([5,6].includes(new Date(`${d}T12:00:00`).getDay()));return d;}
function validDate(v){return /^\d{4}-\d{2}-\d{2}$/.test(String(v||""));}
function uid(prefix="id"){return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,9)}`;}
function notify(msg,type="ok"){let n=document.getElementById("appNotice");if(!n){n=document.createElement("div");n.id="appNotice";n.style.cssText="position:fixed;top:18px;left:18px;z-index:9999;max-width:380px;padding:12px 16px;border-radius:12px;background:#fff;box-shadow:0 8px 30px #0002;font-weight:700";document.body.appendChild(n);}n.textContent=msg;n.style.border=`2px solid ${type==="error"?"#b42318":"#17834b"}`;clearTimeout(window.__noticeTimer);window.__noticeTimer=setTimeout(()=>n.remove(),3500);}
function loginCode(){return settings().loginCode||"1234";}
function isLoggedIn(){return sessionStorage.getItem(AUTH_KEY)==="1";}
function logout(){sessionStorage.removeItem(AUTH_KEY);location.href="login.html";}
function requireAuth(){if(!location.pathname.endsWith("login.html")&&!isLoggedIn())location.replace("login.html");}
function toggleMenu(){document.querySelector(".sidebar")?.classList.toggle("open");}
function studentById(id){return db().students.find(s=>String(s.id)===String(id));}
function paymentsFor(id){return db().payments.filter(p=>String(p.studentId)===String(id));}
function paidFor(id){return paymentsFor(id).reduce((a,p)=>a+Number(p.amount||0),0);}
function remainingFor(s){return Math.max(Number(s?.fees||0)-paidFor(s?.id),0);}
function normalizePhone(v){return String(v||"").replace(/\s+/g,"").replace(/^(\+966|00966)/,"0");}
function validatePhone(v){const p=normalizePhone(v);return !p||/^05\d{8}$/.test(p);}
function fillSelect(id,items,withAll=false){const el=document.getElementById(id);if(!el)return;const old=el.value;el.innerHTML=(withAll?'<option value="">الكل</option>':"")+items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");if(items.includes(old))el.value=old;}
function activeStudents(){return db().students.filter(s=>s.active!==false&&String(s.status||"active")!=="archived");}
async function syncFromCloud(showNotice=false){if(cloudSyncing)return cloudPromise;cloudSyncing=true;cloudPromise=(async()=>{try{const data=await apiGetData();const students=(data.students||[]).map(s=>({...s,id:String(s.id||""),number:String(s.number||""),name:String(s.name||""),guardianPhone:normalizePhone(s.guardianPhone||""),fees:Number(s.fees||0),created:s.created||s.createdAt||"",nextPaymentDate:s.nextPaymentDate||"",notes:s.notes||"",active:String(s.status||"active")!=="archived",status:s.status||"active"}));const payments=(data.payments||[]).map(p=>({...p,id:String(p.id||""),studentId:String(p.studentId||""),amount:Number(p.amount||0),date:String(p.date||""),method:String(p.method||""),ref:String(p.ref||""),notes:String(p.notes||"")}));const remoteSettings=data.settings||[];const s=settings();remoteSettings.forEach(x=>{if(x.key==="loginCode")s.loginCode=String(x.value||"");});const levels=(data.levels||[]).filter(x=>String(x.status||"active")==="active").map(x=>String(x.name||"")).filter(Boolean);const methods=(data.methods||[]).filter(x=>String(x.status||"active")==="active").map(x=>String(x.name||"")).filter(Boolean);if(levels.length)s.levels=levels;if(methods.length)s.methods=methods;saveSettings(s);saveDB({students,payments});if(showNotice)notify("تم تحديث البيانات من Google Sheets");return data;}catch(e){if(showNotice)notify("تعذر الاتصال بـ Google Sheets. تم استخدام البيانات المحفوظة محليًا.","error");throw e;}finally{cloudSyncing=false;}})();return cloudPromise;}
async function cloudWrite(action,payload){try{const result=await apiPost(action,payload);await syncFromCloud(false);return result;}catch(e){notify(e.message||"تعذر حفظ البيانات على الخادم","error");throw e;}}
function openStudent(id){const modal=document.getElementById("studentModal");if(!modal)return;const s=id?studentById(id):null;document.getElementById("studentModalTitle").textContent=s?"تعديل بيانات الطالب":"إضافة طالب";document.getElementById("sId").value=s?.id||"";document.getElementById("sNumber").value=s?.number||"";document.getElementById("sName").value=s?.name||"";document.getElementById("sGuardianPhone").value=s?.guardianPhone||"";document.getElementById("sCreated").value=s?.created||today();document.getElementById("sFees").value=s?.fees??"";document.getElementById("sNotes").value=s?.notes||"";if(document.getElementById("sDueDate"))document.getElementById("sDueDate").value=s?.nextPaymentDate||nextWorkday(today());fillSelect("sLevel",settings().levels);if(s)document.getElementById("sLevel").value=s.level||settings().levels[0];modal.classList.add("show");}
function closeStudent(){document.getElementById("studentModal")?.classList.remove("show");}
async function saveStudent(btn){if(btn?.disabled)return;const name=document.getElementById("sName")?.value.trim(),number=document.getElementById("sNumber")?.value.trim(),level=document.getElementById("sLevel")?.value,created=document.getElementById("sCreated")?.value,fees=Number(document.getElementById("sFees")?.value||0),phone=normalizePhone(document.getElementById("sGuardianPhone")?.value),due=document.getElementById("sDueDate")?.value,notes=document.getElementById("sNotes")?.value.trim(),id=document.getElementById("sId")?.value;if(!name)return notify("اكتب اسم الطالب","error");if(!number)return notify("اكتب رقم الطالب","error");if(!level)return notify("اختر المرحلة","error");if(!validDate(created))return notify("تاريخ التسجيل غير صحيح","error");if(!Number.isFinite(fees)||fees<0)return notify("الرسوم غير صحيحة","error");if(!validatePhone(phone))return notify("رقم ولي الأمر يجب أن يكون 05xxxxxxxx","error");if(due&&!validDate(due))return notify("تاريخ الدفعة القادمة غير صحيح","error");const dup=db().students.find(s=>String(s.number)===number&&String(s.id)!==String(id)&&s.active!==false);if(dup)return notify("رقم الطالب مستخدم بالفعل","error");const obj={id:id||uid("stu"),number,name,guardianPhone:phone,level,created,fees,nextPaymentDate:due||nextWorkday(created),notes,status:"active"};btn.disabled=true;try{await cloudWrite(id?"updateStudent":"addStudent",obj);closeStudent();renderStudents();notify(id?"تم تعديل بيانات الطالب":"تم تسجيل الطالب بنجاح");}catch(e){}finally{btn.disabled=false;}}
async function initStudentPage(){requireAuth();fillSelect("sLevel",settings().levels);fillSelect("levelFilter",settings().levels,true);renderStudents();try{await syncFromCloud(false);fillSelect("sLevel",settings().levels);fillSelect("levelFilter",settings().levels,true);renderStudents();}catch(e){}const edit=new URLSearchParams(location.search).get("edit");if(edit)setTimeout(()=>openStudent(edit),0);}
function renderStudents(){const d=db(),q=(document.getElementById("studentSearch")?.value||"").trim().toLowerCase(),lf=document.getElementById("levelFilter")?.value||"",rows=activeStudents().filter(s=>(!q||[s.name,s.number,s.guardianPhone].some(v=>String(v||"").toLowerCase().includes(q)))&&(!lf||s.level===lf)),body=document.getElementById("studentsTable");if(body)body.innerHTML=rows.map(s=>`<tr><td>${esc(s.number)}</td><td><a href="student.html?id=${encodeURIComponent(s.id)}">${esc(s.name)}</a></td><td>${esc(s.guardianPhone||"-")}</td><td>${esc(s.level)}</td><td>${esc(s.created||"-")}</td><td>${money(s.fees)} ريال</td><td>${money(paidFor(s.id))} ريال</td><td>${money(remainingFor(s))} ريال</td><td><button class="outline" onclick="openStudent('${esc(s.id)}')">تعديل</button> <button class="outline danger" onclick="archiveStudent('${esc(s.id)}')">أرشفة</button></td></tr>`).join("")||'<tr><td colspan="9">لا توجد نتائج</td></tr>';const cards=document.getElementById("levelCards");if(cards)cards.innerHTML=settings().levels.map(l=>{const a=activeStudents().filter(s=>s.level===l);return `<div class="stat"><small>${esc(l)}</small><strong>${a.length}</strong><em>${money(a.reduce((x,s)=>x+remainingFor(s),0))} ريال متبقي</em></div>`}).join("");}
async function archiveStudent(id){const s=studentById(id);if(!s||!confirm(`أرشفة الطالب ${s.name}؟ لن يتم حذف سجل المدفوعات.`))return;try{await cloudWrite("deleteStudent",{id});renderStudents();notify("تمت أرشفة الطالب مع حفظ سجله المالي");}catch(e){}}
function initPayment(){requireAuth();const sel=document.getElementById("pStudent");if(sel)sel.innerHTML='<option value="">اختر الطالب</option>'+activeStudents().map(s=>`<option value="${esc(s.id)}">${esc(s.name)} — ${esc(s.number)}</option>`).join("");if(document.getElementById("pDate"))document.getElementById("pDate").value=today();if(document.getElementById("pMethod"))fillSelect("pMethod",settings().methods);showBalance();syncFromCloud(false).then(()=>initPaymentSelects()).catch(()=>{});}
function initPaymentSelects(){const sel=document.getElementById("pStudent");if(sel)sel.innerHTML='<option value="">اختر الطالب</option>'+activeStudents().map(s=>`<option value="${esc(s.id)}">${esc(s.name)} — ${esc(s.number)}</option>`).join("");fillSelect("pMethod",settings().methods);showBalance();}
function showBalance(){const s=studentById(document.getElementById("pStudent")?.value),b=document.getElementById("balanceBox");if(!b)return;b.textContent=s?`المتبقي على ${s.name}: ${money(remainingFor(s))} ريال`:"اختر الطالب لمعرفة المتبقي";}
async function savePayment(btn){if(btn?.disabled)return;const sid=document.getElementById("pStudent")?.value,date=document.getElementById("pDate")?.value,amount=Number(document.getElementById("pAmount")?.value||0),method=document.getElementById("pMethod")?.value,ref=document.getElementById("pRef")?.value.trim(),notes=document.getElementById("pNotes")?.value.trim(),s=studentById(sid);if(!s)return notify("اختر الطالب","error");if(!validDate(date))return notify("تاريخ الدفع غير صحيح","error");if(!Number.isFinite(amount)||amount<=0)return notify("أدخل مبلغًا أكبر من صفر","error");if(!settings().methods.includes(method))return notify("طريقة الدفع غير معتمدة","error");const rem=remainingFor(s);if(amount>rem)return notify(`المبلغ أكبر من المتبقي (${money(rem)} ريال)`,"error");if(ref&&db().payments.some(p=>p.ref===ref))return notify("رقم المرجع مستخدم مسبقًا","error");btn.disabled=true;try{await cloudWrite("addPayment",{id:uid("pay"),studentId:sid,date,amount,method,ref,notes});notify("تم حفظ الدفعة");setTimeout(()=>location.href=`student.html?id=${encodeURIComponent(sid)}`,300);}catch(e){}finally{btn.disabled=false;}}
function initFilters(){requireAuth();fillSelect("payLevel",settings().levels,true);fillSelect("payMethod",settings().methods,true);syncFromCloud(false).then(()=>{fillSelect("payLevel",settings().levels,true);fillSelect("payMethod",settings().methods,true);renderPayments();}).catch(()=>{});}
function renderPayments(){const d=db(),q=(document.getElementById("paySearch")?.value||"").trim().toLowerCase(),level=document.getElementById("payLevel")?.value||"",method=document.getElementById("payMethod")?.value||"",from=document.getElementById("fromDate")?.value||"",to=document.getElementById("toDate")?.value||"",rows=d.payments.filter(p=>{const s=studentById(p.studentId);return !!s&&(!q||s.name.toLowerCase().includes(q)||String(s.number).includes(q))&&(!level||s.level===level)&&(!method||p.method===method)&&(!from||p.date>=from)&&(!to||p.date<=to);}),body=document.getElementById("paymentsTable");if(!body)return;body.innerHTML=rows.slice().sort((a,b)=>b.date.localeCompare(a.date)||String(b.createdAt).localeCompare(String(a.createdAt))).map(p=>{const s=studentById(p.studentId);return `<tr><td>${esc(p.date)}</td><td>${esc(s?.name||"-")}</td><td>${esc(s?.level||"-")}</td><td>${money(p.amount)} ريال</td><td>${esc(p.method)}</td><td>${esc(p.ref||"-")}</td><td><button class="outline" onclick="editPayment('${esc(p.id)}')">تعديل</button> <button class="outline danger" onclick="deletePayment('${esc(p.id)}')">حذف</button></td></tr>`}).join("")||'<tr><td colspan="7">لا توجد دفعات</td></tr>';}
async function editPayment(id){const p=db().payments.find(x=>String(x.id)===String(id));if(!p)return;const n=prompt("المبلغ الجديد",p.amount);if(n===null)return;const amount=Number(n),s=studentById(p.studentId),other=paidFor(s.id)-Number(p.amount);if(!Number.isFinite(amount)||amount<=0)return notify("المبلغ غير صحيح","error");if(amount>Math.max(Number(s.fees||0)-other,0))return notify("المبلغ يتجاوز المتبقي","error");try{await cloudWrite("updatePayment",{id:p.id,studentId:p.studentId,date:p.date,amount,method:p.method,ref:p.ref,notes:p.notes});renderPayments();notify("تم تعديل الدفعة");}catch(e){}}
async function deletePayment(id){const p=db().payments.find(x=>String(x.id)===String(id));if(!p||!confirm("حذف الدفعة نهائيًا؟"))return;try{await cloudWrite("deletePayment",{id});renderPayments();notify("تم حذف الدفعة");}catch(e){}}
let reportPeriod="day";
function periodRange(period){const end=today(),start=period==="day"?end:period==="week"?addDays(end,-6):`${end.slice(0,7)}-01`;return {start,end};}
function setReportPeriod(period,btn){reportPeriod=period;document.querySelectorAll(".report-tabs button").forEach(b=>b.classList.remove("active"));btn?.classList.add("active");renderReports();}
function renderReports(){requireAuth();const d=db(),{start,end}=periodRange(reportPeriod),active=activeStudents(),newStudents=active.filter(s=>s.created>=start&&s.created<=end),old=active.filter(s=>s.created<start),payments=d.payments.filter(p=>p.date>=start&&p.date<=end);const title=document.getElementById("reportPeriodTitle");if(title)title.textContent=`التقرير ${reportPeriod==="day"?"اليومي":reportPeriod==="week"?"الأسبوعي":"الشهري"}`;const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set("oldCount",old.length);set("newCount",newStudents.length);set("totalCount",active.length);const nl=document.getElementById("newStudentsTable");if(nl)nl.innerHTML=newStudents.map(s=>`<tr><td>${esc(s.number)}</td><td>${esc(s.name)}</td><td>${esc(s.level)}</td><td>${esc(s.created)}</td><td>${money(s.fees)} ريال</td></tr>`).join("")||'<tr><td colspan="5">لا توجد تسجيلات جديدة</td></tr>';const mr=document.getElementById("methodReport");if(mr)mr.innerHTML=settings().methods.map(m=>{const ps=payments.filter(p=>p.method===m);return `<tr><td>${esc(m)}</td><td>${ps.length}</td><td>${money(ps.reduce((a,p)=>a+Number(p.amount||0),0))} ريال</td></tr>`}).join("");const lr=document.getElementById("levelReport");if(lr)lr.innerHTML=settings().levels.map(l=>{const ss=active.filter(s=>s.level===l),fees=ss.reduce((a,s)=>a+Number(s.fees||0),0),paid=ss.reduce((a,s)=>a+paidFor(s.id),0);return `<tr><td>${esc(l)}</td><td>${ss.length}</td><td>${money(fees)} ريال</td><td>${money(paid)} ريال</td><td>${money(Math.max(fees-paid,0))} ريال</td></tr>`}).join("");}
function initReports(){requireAuth();renderReports();syncFromCloud(false).then(renderReports).catch(()=>{});}
function buildSchedule(d){return d.students.filter(s=>s.active!==false&&String(s.status||"active")!=="archived").map(s=>{const date=validDate(s.nextPaymentDate)?s.nextPaymentDate:nextWorkday(today());return {name:s.name,level:s.level,date,day:weekday(date),amount:remainingFor(s),id:s.id};}).filter(x=>x.amount>0).sort((a,b)=>a.date.localeCompare(b.date));}
function initSchedule(){requireAuth();fillSelect("schLevel",settings().levels,true);renderSchedule();syncFromCloud(false).then(()=>{fillSelect("schLevel",settings().levels,true);renderSchedule();}).catch(()=>{});}
function renderSchedule(){const q=(document.getElementById("schSearch")?.value||"").trim().toLowerCase(),l=document.getElementById("schLevel")?.value||"",body=document.getElementById("scheduleTable");if(!body)return;const rows=buildSchedule(db()).filter(x=>(!q||x.name.toLowerCase().includes(q))&&(!l||x.level===l));body.innerHTML=rows.map(x=>`<tr><td><a href="student.html?id=${encodeURIComponent(x.id)}">${esc(x.name)}</a></td><td>${esc(x.level)}</td><td>${esc(x.date)}</td><td>${esc(x.day)}</td><td>${money(x.amount)} ريال</td></tr>`).join("")||'<tr><td colspan="5">لا توجد مواعيد مستحقة</td></tr>';}
function renderSettings(){requireAuth();const s=settings(),lv=document.getElementById("levelsList"),mt=document.getElementById("methodsList");if(lv)lv.innerHTML=s.levels.map((x,i)=>`<div class="setting-row"><span>${esc(x)}</span><button class="outline" onclick="removeLevel(${i})">حذف</button></div>`).join("");if(mt)mt.innerHTML=s.methods.map((x,i)=>`<div class="setting-row"><span>${esc(x)}</span><button class="outline" onclick="removeMethod(${i})">حذف</button></div>`).join("");}
async function addLevel(){const x=prompt("اسم المستوى");if(!x?.trim())return;const name=x.trim(),s=settings();if(s.levels.includes(name))return notify("المستوى موجود بالفعل","error");try{await cloudWrite("addLevel",{name});renderSettings();notify("تم إضافة المستوى");}catch(e){}}
async function removeLevel(i){const s=settings();if(s.levels.length<=1)return notify("يجب إبقاء مستوى واحد على الأقل","error");const name=s.levels[i];if(!confirm(`تعطيل المستوى ${name}؟`))return;const remote=(await getRemoteList("levels")).find(x=>x.name===name);if(!remote)return notify("تعذر العثور على المستوى","error");try{await cloudWrite("deleteLevel",{id:remote.id});renderSettings();notify("تم تعطيل المستوى");}catch(e){}}
async function addMethod(){const x=prompt("اسم طريقة الدفع");if(!x?.trim())return;const name=x.trim(),s=settings();if(s.methods.includes(name))return notify("طريقة الدفع موجودة بالفعل","error");try{await cloudWrite("addMethod",{name});renderSettings();notify("تم إضافة طريقة الدفع");}catch(e){}}
async function removeMethod(i){const s=settings();if(s.methods.length<=1)return notify("يجب إبقاء طريقة دفع واحدة على الأقل","error");const name=s.methods[i];if(!confirm(`تعطيل طريقة الدفع ${name}؟`))return;const remote=(await getRemoteList("methods")).find(x=>x.name===name);if(!remote)return notify("تعذر العثور على طريقة الدفع","error");try{await cloudWrite("deleteMethod",{id:remote.id});renderSettings();notify("تم تعطيل طريقة الدفع");}catch(e){}}
async function getRemoteList(type){try{const data=await apiGetData();return data[type]||[];}catch(e){return [];}}
async function changeLoginCode(){const old=prompt("الكود الحالي");if(old!==loginCode())return notify("الكود الحالي غير صحيح","error");const n=prompt("الكود الجديد (4 أحرف/أرقام على الأقل)");if(!n||n.length<4)return notify("الكود يجب أن يكون 4 أحرف/أرقام على الأقل","error");try{await cloudWrite("setSetting",{key:"loginCode",value:n});const s=settings();s.loginCode=n;saveSettings(s);notify("تم تغيير كود الدخول");}catch(e){}}
function initSettings(){requireAuth();renderSettings();syncFromCloud(false).then(renderSettings).catch(()=>{});}
function initDashboard(){requireAuth();renderDashboard();syncFromCloud(false).then(renderDashboard).catch(()=>{});}
function renderDashboard(){const d=db(),active=activeStudents(),fees=active.reduce((a,s)=>a+Number(s.fees||0),0),paid=d.payments.reduce((a,p)=>a+Number(p.amount||0),0),set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set("studentCount",active.length);set("feesTotal",money(fees));set("paidTotal",money(paid));set("remainingTotal",money(Math.max(fees-paid,0)));const lp=document.getElementById("latestPayments");if(lp)lp.innerHTML=d.payments.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,8).map(p=>{const s=studentById(p.studentId);return `<tr><td>${esc(p.date)}</td><td>${esc(s?.name||"-")}</td><td>${money(p.amount)} ريال</td><td>${esc(p.method)}</td></tr>`}).join("")||'<tr><td colspan="4">لا توجد دفعات</td></tr>';const sch=document.getElementById("upcomingSchedule");if(sch)sch.innerHTML=buildSchedule(d).slice(0,8).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.date)}</td><td>${money(x.amount)} ريال</td></tr>`).join("")||'<tr><td colspan="3">لا توجد مواعيد</td></tr>';}
function renderStudentPageDetail(){const id=new URLSearchParams(location.search).get("id"),s=studentById(id);if(!s){const t=document.getElementById("title");if(t)t.textContent="الطالب غير موجود";return;}const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set("title",s.name);set("sl",s.level||"-");set("sf",money(s.fees));set("sp",money(paidFor(id)));set("sr",money(remainingFor(s)));set("sn",s.number||"-");set("sg",s.guardianPhone||"-");set("sd",s.nextPaymentDate||"-");const edit=document.getElementById("editLink");if(edit)edit.href=`students.html?edit=${encodeURIComponent(id)}`;const pay=document.getElementById("payLink");if(pay)pay.href=`payment.html?student=${encodeURIComponent(id)}`;const history=document.getElementById("history");if(history){const ps=paymentsFor(id).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date)));history.innerHTML=ps.map(p=>`<tr><td>${esc(p.date)}</td><td>${money(p.amount)} ريال</td><td>${esc(p.method)}</td><td>${esc(p.ref||"-")}</td><td>${esc(p.notes||"-")}</td></tr>`).join("")||'<tr><td colspan="5">لا توجد دفعات</td></tr>';}}
function initStudentDetail(){requireAuth();renderStudentPageDetail();syncFromCloud(false).then(renderStudentPageDetail).catch(()=>{});}
(function(){try{if(location.pathname.endsWith("login.html")){if(isLoggedIn())location.replace("index.html");}else{requireAuth();syncFromCloud(false).then(()=>{const p=location.pathname;if(p.endsWith("students.html"))renderStudents();else if(p.endsWith("payments.html"))renderPayments();else if(p.endsWith("schedule.html"))renderSchedule();else if(p.endsWith("reports.html"))renderReports();else if(p.endsWith("settings.html"))renderSettings();else if(p.endsWith("student.html"))renderStudentPageDetail();else if(p.endsWith("index.html")||p==="/"||p.endsWith("/"))renderDashboard();}).catch(()=>{});}}catch(e){console.error(e);}})();