/* Automatic child ID/number: generated by the system and never manually edited. */
(function () {
  function nextStudentNumber() {
    try {
      const data = typeof db === "function" ? db() : { students: [] };
      const nums = (data.students || [])
        .map(s => parseInt(String(s.number || "").trim(), 10))
        .filter(Number.isFinite);
      return String(nums.length ? Math.max.apply(null, nums) + 1 : 1001);
    } catch (e) {
      return "1001";
    }
  }

  function prepareNumberField() {
    const input = document.getElementById("sNumber");
    if (!input) return;
    input.readOnly = true;
    input.setAttribute("aria-readonly", "true");
    input.title = "يتم إنشاء رقم الطفل تلقائيًا ولا يمكن تعديله";
    const id = document.getElementById("sId")?.value;
    if (!id && !input.value) input.value = nextStudentNumber();
  }

  function patchSaveStudent() {
    if (typeof window.saveStudent !== "function" || window.saveStudent.__autoIdPatched) return;
    const original = window.saveStudent;
    const wrapped = function (btn) {
      const id = document.getElementById("sId")?.value;
      const input = document.getElementById("sNumber");
      if (!id && input) {
        input.value = nextStudentNumber();
      }
      return original(btn);
    };
    wrapped.__autoIdPatched = true;
    window.saveStudent = wrapped;
  }

  function initAutoId() {
    prepareNumberField();
    patchSaveStudent();
    const modal = document.getElementById("studentModal");
    if (modal) new MutationObserver(() => {
      prepareNumberField();
      patchSaveStudent();
    }).observe(modal, { attributes: true, subtree: true, childList: true });
  }

  document.addEventListener("DOMContentLoaded", initAutoId);
  window.addEventListener("load", initAutoId);
})();
