/* Automatic child ID/number: generated by the system and never manually edited. */
(function () {
  let observerStarted = false;

  function nextStudentNumber() {
    try {
      const data = typeof db === "function" ? db() : { students: [] };
      const nums = (data.students || [])
        .map(s => parseInt(String(s.number || "").trim(), 10))
        .filter(Number.isFinite);
      return String(nums.length ? Math.max.apply(null, nums) + 1 : 1001);
    } catch (e) {
      return "1001";
    }
  }

  function prepareNumberField() {
    const input = document.getElementById("sNumber");
    if (!input) return;
    if (!input.readOnly) input.readOnly = true;
    if (input.getAttribute("aria-readonly") !== "true") input.setAttribute("aria-readonly", "true");
    const title = "يتم إنشاء معرف الطفل تلقائيًا ولا يمكن تعديله";
    if (input.title !== title) input.title = title;
    const id = document.getElementById("sId")?.value;
    if (!id && !input.value) input.value = nextStudentNumber();
  }

  function patchSaveStudent() {
    if (typeof window.saveStudent !== "function" || window.saveStudent.__autoIdPatched) return;
    const original = window.saveStudent;
    const wrapped = function (btn) {
      const id = document.getElementById("sId")?.value;
      const input = document.getElementById("sNumber");
      if (!id && input) input.value = nextStudentNumber();
      return original(btn);
    };
    wrapped.__autoIdPatched = true;
    window.saveStudent = wrapped;
  }

  function initAutoId() {
    prepareNumberField();
    patchSaveStudent();
    if (observerStarted) return;
    const modal = document.getElementById("studentModal");
    if (!modal) return;
    observerStarted = true;
    new MutationObserver(() => {
      prepareNumberField();
      patchSaveStudent();
    }).observe(modal, { childList: true, subtree: true });
  }

  document.addEventListener("DOMContentLoaded", initAutoId, { once: true });
  window.addEventListener("load", initAutoId, { once: true });
})();
